name: Build images (DockerHub, Windows)

on:
  release:
    types:
      - published
  push:
    branches:
      - 'trunk'
    paths:
      - 'Dockerfiles/*/windows/*'
      - '.github/workflows/images_build_windows.yml'

defaults:
  run:
    shell: pwsh

env:
  DOCKER_REPOSITORY: "zabbix"
  LATEST_BRANCH: ${{ github.event.repository.default_branch }}
  BASE_BUILD_NAME: "build-base"

jobs:
  init_build:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.os.outputs.list }}
      components: ${{ steps.components.outputs.list }}
      is_default_branch: ${{ steps.branch_info.outputs.is_default }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Check build.json file
        id: build_exists
        run: |
            if (-not(Test-Path -Path "./build.json" -PathType Leaf)) {
                throw "::error::File build.json is missing"
            }

      - name: Prepare Operating System list
        id: os
        run: |
            $os_list='["windows"]'

            echo "::set-output name=list::$os_list"

      - name: Prepare Zabbix component list
        id: components
        run: |
            $component_list='["agent","agent2"]'

            echo "::set-output name=list::$component_list"

      - name: Get branch info
        id: branch_info
        uses: tj-actions/branch-names@v5

  build_base:
    timeout-minutes: 70
    name: Build base on ${{ matrix.os }}
    needs: init_build
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.init_build.outputs.os) }}
        build: ${{ fromJson(needs.init_build.outputs.components) }}

    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPOSITORY }}/zabbix-${{ env.BASE_BUILD_NAME }}
          tags: |
            type=ref,event=branch,prefix=${{ matrix.os }}-
            type=ref,event=branch,suffix=-${{ matrix.os }}
          flavor: |
            latest=false

      - name: Build ${{ env.BASE_BUILD_NAME }}/${{ matrix.build }}-${{ matrix.os }} and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: ./Dockerfiles/${{ env.BASE_BUILD_NAME }}/${{ matrix.os }}
          file: ./Dockerfiles/${{ env.BASE_BUILD_NAME }}/${{ matrix.os }}/Dockerfile.${{ matrix.build }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.revision=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            org.opencontainers.image.created=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}

      - name: Image digest
        run: |
            echo ${{ steps.docker_build.outputs.digest }}
            echo "${{ steps.docker_build.outputs.digest }}" > ${{ env.BASE_BUILD_NAME }}_${{ matrix.os }}

      - name: Upload SHA256 tag
        uses: actions/upload-artifact@v2.2.4
        with:
         name: ${{ env.BASE_BUILD_NAME }}_${{ matrix.os }}
         path: ${{ env.BASE_BUILD_NAME }}_${{ matrix.os }}
         if-no-files-found: error

  build_base_database:
    timeout-minutes: 70
    needs: [ "build_base", "init_build"]
    name: Build ${{ matrix.build }} base on ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        build: ${{ fromJson(needs.init_build.outputs.database) }}
        os: ${{ fromJson(needs.init_build.outputs.os) }}

    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Platform list
        id: platform
        run: |
            platform_list=$(jq -r '.os.${{ matrix.os }} | join(",")' "./build.json")

            echo ::set-output name=list::$platform_list

      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPOSITORY }}/zabbix-${{ matrix.build }}
          tags: |
            type=ref,event=branch,prefix=${{ matrix.os }}-
            type=ref,event=branch,suffix=-${{ matrix.os }}
          flavor: |
            latest=false

      - name: Download SHA256 tag  build-base:${{ matrix.os }}
        uses: actions/download-artifact@v2.0.10
        with:
          name: build-base_${{ matrix.os }}

      - name: Retrieve build-base:${{ matrix.os }} SHA256 tag
        id: base_build
        run: |
          BASE_TAG=$(cat build-base_${{ matrix.os }})
          BUILD_BASE_IMAGE=${{ env.DOCKER_REPOSITORY }}/zabbix-build-base@${BASE_TAG}

          echo ::set-output name=base_tag::${BASE_TAG}
          echo ::set-output name=base_build_image::${BUILD_BASE_IMAGE}

      - name: Build ${{ matrix.build }}/${{ matrix.os }} and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./Dockerfiles/${{ matrix.build }}/${{ matrix.os }}
          file: ./Dockerfiles/${{ matrix.build }}/${{ matrix.os }}/Dockerfile
          platforms: ${{ steps.platform.outputs.list }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          build-args: BUILD_BASE_IMAGE=${{ steps.base_build.outputs.base_build_image }}
          labels: |
            org.opencontainers.image.revision=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            org.opencontainers.image.created=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}

      - name: Image digest
        run: |
            echo ${{ steps.docker_build.outputs.digest }}
            echo "${{ steps.docker_build.outputs.digest }}" > ${{ matrix.build }}_${{ matrix.os }}

      - name: Upload SHA256 tag
        uses: actions/upload-artifact@v2.2.4
        with:
         name: ${{ matrix.build }}_${{ matrix.os }}
         path: ${{ matrix.build }}_${{ matrix.os }}
         if-no-files-found: error

  build_images:
    timeout-minutes: 70
    needs: [ "build_base_database", "init_build"]
    name: Build ${{ matrix.build }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: ${{ fromJson(needs.init_build.outputs.components) }}
        os: ${{ fromJson(needs.init_build.outputs.os) }}

    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Platform list
        id: platform
        run: |
            # Chromium on Alpine is available only on linux/amd64, linux/arm64 platforms
            if [ "${{ matrix.os }}" == "alpine" ] && [ "${{ matrix.build }}" == "web-service" ]; then
                platform_list="linux/amd64,linux/arm64"
            else
                platform_list=$(jq -r '.os.${{ matrix.os }} | join(",")' "./build.json")
            fi

            echo ::set-output name=list::$platform_list

      - name: Detect Build Base Image
        id: build_base_image
        run: |
          BUILD_BASE=$(jq -r '.components."${{ matrix.build }}"' "./build.json")

          echo ::set-output name=build_base::${BUILD_BASE}

      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPOSITORY }}/zabbix-${{ matrix.build }}
          tags: |
            type=ref,event=branch,prefix=${{ matrix.os }}-
            type=ref,event=branch,suffix=-${{ matrix.os }}
          flavor: |
            latest=false

      - name: Download SHA256 tag for ${{ steps.build_base_image.outputs.build_base }}:${{ matrix.os }}
        uses: actions/download-artifact@v2.0.10
        if: ${{ matrix.build != 'snmptraps' }}
        with:
          name: ${{ steps.build_base_image.outputs.build_base }}_${{ matrix.os }}

      - name: Retrieve ${{ steps.build_base_image.outputs.build_base }}:${{ matrix.os }} SHA256 tag
        id: base_build
        if: ${{ matrix.build != 'snmptraps' }}
        run: |
          BASE_TAG=$(cat ${{ steps.build_base_image.outputs.build_base }}_${{ matrix.os }})
          BUILD_BASE_IMAGE=${{ env.DOCKER_REPOSITORY }}/zabbix-${{ steps.build_base_image.outputs.build_base }}@${BASE_TAG}

          echo ::set-output name=base_tag::${BASE_TAG}
          echo ::set-output name=base_build_image::${BUILD_BASE_IMAGE}

      - name: Build ${{ matrix.build }}/${{ matrix.os }} and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./Dockerfiles/${{ matrix.build }}/${{ matrix.os }}
          file: ./Dockerfiles/${{ matrix.build }}/${{ matrix.os }}/Dockerfile
          platforms: ${{ steps.platform.outputs.list }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          build-args: BUILD_BASE_IMAGE=${{ steps.base_build.outputs.base_build_image }}
          labels: |
            org.opencontainers.image.revision=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            org.opencontainers.image.created=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
